import Header from "@/components/Header";

import type { Metadata } from "next";
import { Lexend_Mega } from "next/font/google";
import "./globals.css";

const LexendMega = Lexend_Mega({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${LexendMega.className} antialiased `}>
        <Header />
        <div id="container-wraper" className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
